### PR TITLE
Hotfix: Display empty search results message on search.gov search

### PR DESCRIPTION
**Pull request by erinysong**
## Changes proposed in this pull request:
- Delivers #126 requirement: `Display custom message when no results are found.`
- Fixes bug that caused search results to not get properly identified on the beta.get.gov site due to a bug in how we were interpreting that the search-results HTML element was empty. 

**Explanation**
The "No results found" message displays when there are no childNodes in the search-results element. Earlier, the way that the search-results element was formatted was formatted as:
```
<ul id="search-results" class= "usa-list usa-list--unstyled">
</ul>
```
which the JS interpreter translated as an empty line instead of just a formatting preference. The issue was fixed by removing the indent.
[Note the any security considerations here, or make note of why there are none]

### CODE REVIEW

**Comment by michelle-rago** [comment]
You fixed it!! 😄

**Comment by erinysong** [comment]
It was a silly formatting error that turned out to affect a lot more than expected but yes we managed to workaround it!! Thank you for sharing the cloud-pages thread - it helped a lot to debug the issue

**Review by michelle-rago — APPROVED** [review]
Looks great! I'll update the actual text in a different PR.

**Comment by caleywoods** [comment]
Great job @erinysong and @michelle-rago !!!

**Comment by michelle-rago** [comment]
Thanks for your help, @caleywoods!

**Pull request merged**
