### PR TITLE
Issue #170 - Sub-nav for About/Jobs side menu

### LINKED ISSUE #170: Add ability to have subnav on get.gov pages
We'd like to add subnav on get.gov pages. For example, the software engineering links in this screenshot would be indented under the Jobs section. 

Image

An 11ty site example with subnav
- The [subnav on these pages](https://guides.18f.gov/engineering/our-approach/architecture-reviews/) are all anchor links.  We want to add subnav that will link to new pages (not anchor links). 

A/C

- [ ] https://get.gov/about/jobs/ will only show two engineering positions when on https://get.gov/about/jobs/ but not on https://get.gov/about/

Additional Context:
- Refer to DNS Child pages for example of how this has been implemented already.
- We'll use this work as an example for future design work that requires a subnav

### PR DESCRIPTION
**Pull request by CocoByte**
## Ticket

Resolves #170

## Changes

- Upgraded @11ty/eleventy-navigation plugin
- Changed loading of nav items to utilize tags instead of keys (tags = keys before this upgrade) & added "parent" property to jobs subitems
- Added logic to side nav to drill down into nav children

## Code Review Verification Steps

Navigate to /about.  Verify the following;
- [x] a sublist of "senior software developer" and "software developer" opens when you click on "Jobs" and hides when you navigate to another item sidenav.
- [x] navigating to either job listing keeps this submenu open and navs to the expected job listing pages

Navigate to /about/jobs directly in the url. Verify the following;
- [x] the sublist of "senior software developer" and "software developer" is already opened with ".Gov jobs" selected in the side menu.

image

Navigate to /about/jobs/senior-software-engineer/.  Verify the following;
- [x] the sublist of "senior software developer" and "software developer" is already opened with "senior software developer" selected in the side menu.

#### Satisfied acceptance criteria and met development standards

- [X] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [X] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [X Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

### CODE REVIEW

**Comment by michelle-rago** [comment]
@CocoByte This looks great! Thank you!! The sub-nav items look a little small to me. @gabydisarli Can you take a look and see if you think they should be the same size as the sidenav?

**Review by neilmb — APPROVED** [review]
This looks just right. Thanks @CocoByte

**Comment by gabydisarli** [comment]
> @CocoByte This looks great! Thank you!!
> 
> The sub-nav items look a little small to me. @gabydisarli Can you take a look and see if you think they should be the same size as the sidenav?
> 
> @kristinacyin What do you think about the font size?

Good eye! Yes, it looks like its using maybe the caption size, I'm getting 14.88 px on my end. @CocoByte can you adjust the subnav here to be the same font size as the parent pages? 
Screenshot 2024-02-02 at 10 12 28 AM

That being said, I see that we have the same styling in the side nav on manage.get.gov, I'm going to make a ticket to update those child pages as well.

**Comment by gabydisarli** [comment]
@CocoByte send me a Slack when you've made the change and I can take a look

**Review by gabydisarli — APPROVED** [review]

**Pull request merged**
