### PR TITLE
ISSUE #132: Check Availability Styling For Mobile

### LINKED ISSUE #132: "Stack" the Check Availability button
### Current Behavior

Currently on mobile, the text on "Check Availability" button overwrites each other

image

### Expected Behavior

We don't want the text to overwrite each other, and should ideally stack like it does in the header.

image

### Steps to Reproduce

1.

### Environment

_No response_

### Additional Context

Slack discussion: https://cisa-corp.slack.com/archives/C05BDEA3C11/p1699652700172109
Reference from OG ticket: https://github.com/cisagov/getgov-home/pull/100

### Issue Links

_No response_

### PR DESCRIPTION
**Pull request by therealslimhsiehdy**
## Ticket

Resolves #132 

## Changes

For the check availability section, we want on mobile devices for users to see the search bar and button to be stacked evenly like these buttons are as an example:

Screenshot 2024-01-09 at 3 33 24 PM

See "Expected Behaviour" section in the ticket for a better reference.

## Context for reviewers

Want users to have a consistent mobile experience.

**Devs** - I had to do a lot of wrapping as our the domain search and availability buttons were customized in their own manner. If there is a better method, please do let me know as I am not as well versed in CSS, but am happy to learn!

## Setup

1. You'll have to `docker-compose down` if you have docker running for anything on `manage.get.gov`
2. Once you have this PR pulled down, in the terminal run `npm run dev`
3. In browser, type in `local:8080`
4. Right click, click `Inspect` and then on the top right (see screenshot) click the Toggle button and choose any mobile device (i.e. iPhone SE for this example)
Screenshot 2024-01-09 at 3 36 16 PM
5. Scroll down to the availability section and see changes there

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

#### Verified that the changes match the design intention

- [x] Checked that the design translated visually
- [x] Checked behavior
- [x] Checked different states (empty, one, some, error)
- [x] Checked for landmarks, page heading structure, and links
- [x] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [x] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [x] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

Tested with both a Samsung and iPhone

Screenshot 2024-01-09 at 3 02 32 PM

Screenshot 2024-01-09 at 3 02 43 PM

### CODE REVIEW

**Review by gabydisarli — COMMENTED** [review]
Looks great!

**Review by gabydisarli — APPROVED** [review]
Accidentally clicked comment before, here's my actual approval 😆

**Review by zandercymatics — APPROVED** [review]
LGTM, I think all of your changes are reasonable here. I think element wrapping is totally understandable in this context. If you'd like to avoid that, I would recommend reaching out to Rachid as he is very knowledgeable about uswds in terms flex, and things like that

**Comment by gabydisarli** [comment]
@therealslimhsiehdy heads up, the button on mobile is still acting funky. Any idea what happened here? https://github.com/cisagov/get.gov/issues/225

**Pull request merged**
