### PR TITLE
Updates on account management page

### PR DESCRIPTION
**Pull request by Katherine-Osos**
## Changes proposed in this pull request:
Content updates to match [Google doc](https://docs.google.com/document/d/1oxKgGR6mrVSQEwmrB9kNrhrhKAQ4-9fw0xxCQoT_qxc/edit). Most of the text was updated, so all content should be reviewed for this PR.

(part of content review for [#1283](https://github.com/cisagov/manage.get.gov/issues/1283))

### CODE REVIEW

**Comment by Katherine-Osos** [comment]
[Link to review updates](https://federalist-877ab29f-16f6-4f12-961c-96cf064cf070.sites.pages.cloud.gov/preview/cisagov/getgov-home/ko/account-mgmt-updates/help/account-management/)

**Comment by Katherine-Osos** [comment]
@michelle-rago I can't figure out why the "contact us" link is pointing to an old version of that page. When you review my changes, can you check out that link?

**Comment by Katherine-Osos** [comment]
@h-m-f-t Wanted you to be aware of these updates. Overhauling the "Account management" page to reflect messaging we've used in transition communications.

**Review by h-m-f-t — APPROVED** [review]
Excellent changes

**Comment by michelle-rago** [comment]
> @michelle-rago I can't figure out why the "contact us" link is pointing to an old version of that page. When you review my changes, can you check out that link?

@Katherine-Osos We had an old contact file in the help folder. 😇  I deleted it.

**Review by michelle-rago — APPROVED** [review]
Great!!

**Pull request merged**
